version: '3.8'

services:
  vllm-server:
    image: rust-rl-vllm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./multi_model_eval_config.yaml:/app/multi_model_eval_config.yaml:ro
      - ~/.cache/huggingface:/root/.cache/huggingface:ro
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["python", "-m", "vllm.entrypoints.openai.api_server", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped